baseurl = "https://abraham.one/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Abraham Abridged"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-112438396-5"
lastmod = false

[permalinks]
  post = "/:yearday/:title/"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "just sayin'"
  logo = "/images/Abraham150.jpg"
  favicon = "/images/Abraham150.jpg"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = true
  #gcse = "" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Rajiv Abraham"
  website = "https://nela.in/"
  email = "a@brah.am"
  facebook = "939abraham"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "unoabraham"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "unoabraham"
  #reddit = "username"
  #linkedin = "unoabraham"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "unoabraham"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Now"
    url = "page/now/"
    weight = 3

[[menu.main]]
    name = "IndieWeb"
    url = "page/indieweb/"
    weight = 4

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 6

[[menu.main]]
    name = "Search"
    url = "page/search/"
    weight = 7